[tool.poetry]
name = "development"
version = "0.1.0"
description = ""
authors = ["Alina <fakherdinova.alya@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
